name: Ouverture du Drive

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master
  repository_dispatch:
    types: [open]

env:
  TZ: Europe/Paris

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: npm install
        run: |
          npm install
        env:
          CI: true
      
      - name: open drive
        run: |
          npm run open_drive
          cp -r public/images .
        env:
          ALGOLIA_SECRET_KEY: ${{ secrets.ALGOLIA_SECRET_KEY }}
          ODOO_USER: ${{ secrets.ODOO_USER }}
          ODOO_PASSWORD: ${{ secrets.ODOO_PASSWORD }}

      - name: Get Current Date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Mise à jour des produits au jour ${{ env.CURRENT_DATE }}"
          token: ${{ secrets.GITHUB_TOKEN }}
